name: coala_coder_demo
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - airportsdata==20241001
      - annotated-types==0.7.0
      - anthropic==0.42.0
      - anyio==4.7.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==24.3.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - blake3==1.0.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - compressed-tensors==0.8.1
      - dataclasses-json==0.6.7
      - datasets==3.2.0
      - deprecated==1.2.15
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - durationpy==0.9
      - einops==0.8.0
      - evalplus==0.3.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - filelock==3.16.1
      - fire==0.7.0
      - flatbuffers==24.12.23
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gguf==0.10.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.156.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - greenlet==3.1.1
      - grpcio==1.68.1
      - grpcio-status==1.68.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.27.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - interegular==0.3.3
      - jinja2==3.1.5
      - jiter==0.8.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kubernetes==31.0.0
      - langchain==0.3.13
      - langchain-community==0.3.13
      - langchain-core==0.3.28
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.4
      - langsmith==0.2.7
      - lark==1.2.2
      - linkify-it-py==2.0.3
      - lm-format-enforcer==0.10.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - mistral-common==1.5.1
      - mmh3==5.0.1
      - monotonic==1.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - onnxruntime==1.20.1
      - openai==1.58.1
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.10.0.84
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.13
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - posthog==3.7.4
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pyext==0.7
      - pygments==2.18.0
      - pyparsing==3.2.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - ray==2.40.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - restrictedpython==7.4
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.36
      - starlette==0.41.3
      - stop-sequencer==1.2.3
      - sympy==1.13.1
      - tempdir==0.7.1
      - tenacity==9.0.0
      - termcolor==2.5.0
      - textual==1.0.0
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.47.1
      - tree-sitter==0.23.2
      - tree-sitter-python==0.23.6
      - triton==3.1.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.28.0
      - vllm==0.6.6.post1
      - watchfiles==1.0.3
      - websocket-client==1.8.0
      - websockets==14.1
      - wget==3.2
      - wrapt==1.17.0
      - xformers==0.0.28.post3
      - xgrammar==0.1.8
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
