name: coala_coder_demo
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=24.2
  - python=3.10.16
  - setuptools=75.1.0
  - sqlite=3.45.3
  - wheel=0.44.0
  - pip:
      - astunparse==1.6.3
      - charset-normalizer==3.4.1
      - chromadb==0.6.0
      - datasets==3.2.0
      - dill==0.3.8
      - evalplus==0.3.1
      - fastapi==0.115.6
      - fire==0.7.0
      - frozenlist==1.5.0
      - gguf==0.10.0
      - googleapis-common-protos==1.66.0
      - langchain==0.3.13
      - langchain-community==0.3.13
      - langchain-core==0.3.28
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.4
      - matplotlib==3.9.2
      - numpy
      - openai==1.58.1
      - pandas==2.2.3
      - pillow==10.4.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - pydantic==2.10.4
      - pyext==0.7
      - pytest==8.3.4
      - pyyaml==6.0.2
      - regex==2024.11.6
      - restrictedpython==7.4
      - rich==13.9.4
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.47.1
      - tree-sitter==0.23.2
      - tree-sitter-python==0.23.6
      - uvicorn==0.34.0
      - -r requirements.txt
